mainapp/api/urls.py
from django.urls import path

from .api_views import (
    CategoryDetailAPIView, 
    BeerProductListAPIView, 
    BeerProductDetailAPIView, 
    CustomersListAPIView,
    CustomerDetailAPIView,
    CategoryAPIView, 
    PizzaProductAPIView,
    PizzaProductDetailAPIView,
    UserAPIView,
    UserDetailAPIView,
    CartProductAPIView,
    CartProductDetailAPIView,
    CartAPIView,
    CartDetailAPIView,
    OrderAPIView,
    OrderDetailAPIView
)


urlpatterns = [
    path('categories/', CategoryAPIView.as_view(), name='categories_list'),
    path('categories/<str:id>/', CategoryDetailAPIView.as_view(), name='category_detail'),
    path('customers/', CustomersListAPIView.as_view(), name='customers_list'),
    path('customers/<str:user>/', CustomerDetailAPIView.as_view(), name='customer_detail'),
    path('beer/', BeerProductListAPIView.as_view(), name='beer_list'),
    path('beer/<str:id>/', BeerProductDetailAPIView.as_view(), name='beer_detail'),
    path('pizza/', PizzaProductAPIView.as_view(), name='pizza_list'),
    path('pizza/<str:id>/', PizzaProductDetailAPIView.as_view(), name='pizza_detail'),
    path('orders/', OrderAPIView.as_view(), name='orders_list'),
    path('orders/<str:id>/', OrderDetailAPIView.as_view(), name='order_detail'),
    path('carts/', CartAPIView.as_view(), name='carts_list'),
    path('carts/<str:id>/', CartDetailAPIView.as_view(), name='cart_detail'),
    path('cartproducts/', CartProductAPIView.as_view(), name='cartproducts_list'),
    path('cartproducts/<str:id>/', CartProductDetailAPIView.as_view(), name='cartproduct_detail'),
    path('users/', UserAPIView.as_view(), name='users_list'),
    path('users/<str:id>/', UserDetailAPIView.as_view(), name='user_detail'),
]

mainapp/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from .views import (
    BaseView, 
    ProductDetailView, 
    CategoryDetailView, 
    CartView, 
    AddToCartView, 
    DeleteFromCartView,
    ChangeQTYView,
    CheckoutView,
    MakeOrderView,
    PayedOnlineOrderView,
    LoginView,
    RegistrationView,
    ProfileView,
    PizzaAddView,
    BeerAddView,
    ProductUpgradeView,
    SearchResultsView
)

urlpatterns = [
    path("", BaseView.as_view(), name='base'),
    path('products/<str:ct_model>/<str:slug>/', ProductDetailView.as_view(), name='product_detail'),
    path('category/<str:slug>/', CategoryDetailView.as_view(), name='category_detail'),
    path('cart/', CartView.as_view(), name='cart'),
    path('add-to-cart/<str:ct_model>/<str:slug>/',AddToCartView.as_view(), name='add_to_cart'),
    path('delete-from-cart/<str:ct_model>/<str:slug>/',DeleteFromCartView.as_view(), name='delete_from_cart'),
    path('change-qty/<str:ct_model>/<str:slug>/',ChangeQTYView.as_view(), name='change_qty'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('makeorder/', MakeOrderView.as_view(), name='make_order'),
    path('payed-online-order/', PayedOnlineOrderView.as_view(), name='payed_online_order'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page="/"), name='logout'),
    path('registration/', RegistrationView.as_view(), name='registration'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('pizza_add/', PizzaAddView.as_view(), name='pizza_add'),
    path('beer_add/', BeerAddView.as_view(), name='beer_add'),
    path('upgrade/<str:ct_model>/<str:slug>/',ProductUpgradeView.as_view(), name='upgrade'),
    path('search/', SearchResultsView.as_view(), name='search_results'),
]

pizza_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('mainapp.api.urls')),
    path('', include('mainapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from PIL import Image
from io import BytesIO
from django.core.files.uploadedfile import InMemoryUploadedFile
import sys
from django.urls import reverse
from django.utils import timezone
from .custom_logging import logger

from asgiref.sync import sync_to_async

User = get_user_model()
# Create your models here.


#**********
#1 category
#2 porduct
#3 cartproduct
#4 cart
#5 order
#**********
#6 customer
#7 specification(kharakteristics)

# /categories/pizza

def get_models_for_count(*model_names):
    logger.debug('Использование функции подсчёта кол-ва товара')
    return [models.Count(model_name) for model_name in model_names]



def get_product_url(obj, viewname):
    logger.debug('Использование получения урла продукта')
    ct_model = obj.__class__._meta.model_name
    return reverse(viewname, kwargs={'ct_model' : ct_model, 'slug': obj.slug})


class MinResolutionErrorException(Exception):
    pass


class MaxResolutionErrorException(Exception):
    pass

class MaxFileSizeErrorException(Exception):
    pass


class LatestProductManager:

    @staticmethod
    def get_products_for_main_page(*args, **kwargs):
        logger.debug('Взятие продуктов для главной страницф')
        with_respect_to = kwargs.get('with_respect_to')
        products = []
        ct_models = ContentType.objects.filter(model__in=args)
        for ct_model in ct_models:
            model_products = ct_model.model_class()._base_manager.all().order_by('-id')[:5]
            products.extend(model_products)
        if with_respect_to:
            ct_model = ContentType.objects.filter(model=with_respect_to)
            if ct_model.exists():
                if with_respect_to in args:
                    return sorted(
                        products, key=lambda x: x.__class__._meta.model_name.startswith(with_respect_to), reverse=True
                    )
        return products

class LatestProducts:

    objects = LatestProductManager()

class CategoryManager(models.Manager):

    CATEGORY_NAME_COUNT_NAME = {
        'Пицца': 'pizzaproduct__count',
        'Пиво': 'beerproduct__count'
    }

    def get_queryset(self):
        return super().get_queryset()

    def get_categories_for_left_sidebar(self):
        logger.debug('Использование функции get_categories_for_left_sidebar')
        models = get_models_for_count('pizzaproduct', 'beerproduct')
        qs =  list(self.get_queryset().annotate(*models))
        data = [
            dict(name=c.name, url=c.get_absolute_url(), count=getattr(c, self.CATEGORY_NAME_COUNT_NAME[c.name]))
            for c in qs
        ]
        return data

class Category(models.Model):

    name = models.CharField(max_length=255, verbose_name="Имя категории")
    slug = models.SlugField(unique=True, db_index=True) #endpoint
    objects = CategoryManager()

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'slug': self.slug})
    

class Product(models.Model):

    MIN_RESOLUTION = (200, 200)
    MAX_RESOLUTION = (2000, 2000)
    MAX_IMAGE_SIZE = 3145728

    class Meta:
        abstract = True

    category = models.ForeignKey(Category, verbose_name='Категория', on_delete=models.CASCADE)
    title = models.CharField(max_length=255, verbose_name="Наименование", db_index=True)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to='images/')
    description = models.TextField(verbose_name="Описание")
    price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name="Цена")

    def __str__(self):
        return self.title

    def get_model_name(self):
        return self.__class__.__name__.lower()
    


class CartProduct(models.Model):
    user = models.ForeignKey('Customer', verbose_name='Покупатель', on_delete=models.CASCADE, db_index=True)
    cart = models.ForeignKey('Cart', verbose_name='Корзина', on_delete=models.CASCADE, related_name='related_products', db_index=True)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE, db_index=True)
    object_id = models.PositiveIntegerField(db_index=True)
    content_object = GenericForeignKey("content_type", "object_id")
    qty = models.PositiveIntegerField(default=1)
    final_price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name="Общая цена")

    def __str__(self):
        return "Продукт: {} (для корзины)".format(self.content_object.title)
    
    def save(self, *args, **kwargs):
        logger.debug('Подсчёт финальной цены продукта в корзине')
        self.final_price = self.qty * self.content_object.price
        super().save(*args, **kwargs)

class Cart(models.Model):

    owner = models.ForeignKey('Customer', null=True, verbose_name="Владелец", on_delete=models.CASCADE, db_index=True)
    products = models.ManyToManyField(CartProduct, blank=True, related_name="related_cart")
    total_products = models.PositiveIntegerField(default=0)
    final_price = models.DecimalField(max_digits=9, default=0, decimal_places=2, verbose_name="Общая цена")
    in_order = models.BooleanField(default=False, db_index=True)
    for_anonymous_user = models.BooleanField(default=False)

    def __str__(self):
        return str(self.id)


class Customer(models.Model):

    user = models.OneToOneField(User, verbose_name="Пользователь", primary_key=True, on_delete=models.CASCADE, db_index=True)
    phone = models.CharField(max_length=20,verbose_name="Номер телефона", null=True, blank=True)
    address = models.CharField(max_length=255,verbose_name="Адрес", null=True, blank=True)
    # orders = models.ManyToManyField("Order", blank=True, related_name="related_customer", verbose_name="Заказы покупателя")

    def __str__(self):
        return "Покупатель: {} {}".format(self.user.first_name, self.user.last_name)


class PizzaProduct(Product):

    size = models.CharField(max_length=255, verbose_name="Размер")
    board = models.CharField(max_length=255, verbose_name="Борт")
    dough = models.CharField(max_length=255, verbose_name="Тесто")
    vegetarian = models.BooleanField(default=False)
    def __str__(self):
        return "{} : {}".format(self.category.name, self.title)

    def get_absolute_url(self):
        return get_product_url(self, 'product_detail')

class BeerProduct(Product):
    colour = models.CharField(max_length=255, verbose_name="Цвет")
    alcohol_strength = models.CharField(max_length=255, verbose_name="Крепость") 
    filtered = models.CharField(max_length=255, verbose_name="Фильтрация")
    grade = models.CharField(max_length=255, verbose_name="Сорт")   
    def __str__(self):
        return "{} : {}".format(self.category.name, self.title)
    
    def get_absolute_url(self):
        return get_product_url(self, 'product_detail')


class Order(models.Model):

    STATUS_NEW = 'new'
    STATUS_IN_PROGRESS = 'in_progress'
    STATUS_READY = 'is_ready'
    STATUS_COMPLETED = 'completed'
    STATUS_PAYED = 'payed'

    BUYING_TYPE_SELF = 'self'
    BUYING_TYPE_DELIVERY = 'delivery'

    STATUS_CHOICES = (
        (STATUS_PAYED, 'Заказ оплачен'),
        (STATUS_NEW, 'Новый заказ'),
        (STATUS_IN_PROGRESS, 'Заказ в обработке'),
        (STATUS_READY, 'Заказ готов'),
        (STATUS_COMPLETED, 'Заказ выполнен')
    )

    BUYING_TYPE_CHOICES = (
        (BUYING_TYPE_SELF, "Самовывоз"),
        (BUYING_TYPE_DELIVERY, 'Доставка')
    )

    customer = models.ForeignKey('Customer', verbose_name='Покупатель', related_name="related_orders", on_delete=models.CASCADE, db_index=True)
    first_name = models.CharField(max_length=255, verbose_name='Имя')
    last_name = models.CharField(max_length=255, verbose_name='Фамилия')
    phone = models.CharField(max_length=20, verbose_name='Телефон')
    cart = models.OneToOneField(Cart,verbose_name="Корзина", on_delete=models.CASCADE, null=True, blank=True)
    address = models.CharField(max_length=1024, verbose_name='Адрес', null=True, blank=True)
    status = models.CharField(
        max_length=100,
        verbose_name='Статус заказа',
        choices=STATUS_CHOICES,
        default=STATUS_NEW
    )
    buying_type = models.CharField(
        max_length=100,
        verbose_name='Тип заказа',
        choices=BUYING_TYPE_CHOICES,
        default=BUYING_TYPE_SELF
    )
    comment = models.TextField(verbose_name="Комментарий к заказу", null=True, blank=True)
    created_at = models.DateTimeField(auto_now=True, verbose_name="Дата создания заказа")
    order_date = models.DateField(verbose_name="Дата получения заказа", default=timezone.now)

    def __str__(self):
        return str(self.id)

mainapp/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Магазин ПП продуктов</title>

  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <!-- Custom styles for this template -->
  <link href="css/shop-homepage.css" rel="stylesheet">

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
  <script src="https://js.stripe.com/v3/"></script>

</head>
<style>

body {
        padding-top: 56px;
        background: url(https://oir.mobi/uploads/posts/2021-03/thumbs/1616554304_34-p-nezhno-goluboi-fon-odnotonnii-37.png) 100% 100% no-repeat; 
        background-size: cover; 

}



* {
   box-sizing: border-box;
}
.product-item {
   width: 215px;
   text-align: center;
   margin: 0 auto;
   border-bottom: 2px solid #F5F5F5;
   background: rgb(255, 255, 255);
   font-family: "Open Sans";
   transition: .3s ease-in;
}
.product-item:hover {
   border-bottom: 2px solid #fc5a5a;
}
.product-item img {
   display: block;
   width: 100%;
}
.product-list {
   background: hsl(0, 0%, 100%);
   padding: 15px 0;
}
.product-list h3 {
   font-size: 18px;
   font-weight: 400;
   color: #444444;
   margin: 0 0 10px 0;
}
.price {
   font-size: 16px;
   color: #fc5a5a;
   display: block;
   margin-bottom: 12px;
}
.button {
   text-decoration: none;
   display: inline-block;
   padding: 0 12px;
   background: #cccccc;
   color: white;
   text-transform: uppercase;
   font-size: 12px;
   line-height: 28px;
   transition: .3s ease-in;
}
.product-item:hover .button {
   background: #fc5a5a;
}

.colortext {
     color: rgb(33, 139, 165);
     text-align : center;
  }




</style>
<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-blue bg-white fixed-top">
    <a class="navbar-brand" href="{% url 'base' %}">Первая универсальная доставка по всей Беларуси</a>
    <div class="container">
     
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav">
          <li class="nav-item dropdown">
              <a class="nav-link text-blue dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expended="false">
                Категории
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                {% for category in categories %}
                <a class="dropdown-item" href="{{ category.url }}">{{ category.name }}</a>
                {% endfor %}
              </div>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'cart' %}">Корзина: <span class="badge badge-pill badge-danger">{{ cart.products.count }}</span></a>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          <li>
            <form action="{% url 'search_results' %}" method="get">
              <input name="q" type="text" placeholder="Поиск">
            </form>
          </li>
          {% if not request.user.is_authenticated %}
          <li>
            <a class="nav-link text-blue" href="{% url 'login' %}">Авторизация</a>
          </li>
          <li>
            <a class="nav-link text-blue" href="{% url 'registration' %}">Регистрация</a>
          </li>
          {% endif %}
           <li class="nav-item">
             {% if request.user.is_authenticated %}
             <span class="navbar text text-blue">Здравствуйте, <span class="badge badge-danger">
             <a style="text-decoration: none; font-size:14px; color:white;" href="{% url 'profile' %}">{{ request.user.username }}</a>
            </span> | <a style="text-decoration: none; font-size:14px; color:rgb(0, 153, 255);" href="{% url 'logout' %}">Выйти</a></span>
             {% endif %}
           </li>
        </ul>
      </div>
    </div>
  </nav>
 
  <!-- Page Content -->
  
  
  <div class="container">
    {% block content %}
    <!-- <div class="row"> -->
      <marquee direction="right" scrollamount="15"><img width="800" height="400" src="https://hotskidki.by/wp-content/uploads/2021/04/dominos27.04.21.jpg"/><img width="800" height="400" src="https://images.dominos.by/media/uploads/2021/03/24/__852432-min.png" /><img width="800" height="400" src="https://images.dominos.by/media/uploads/2020/10/28/___852432.png"/><img></marquee>
      <!-- <div class="col-lg-3">

        <h1 class="my-4">Магазин ПиццаПиво</h1>

        <h1 class="my-4">Нашу пиццу заказывают знаменитости</h1>
        <img class="card-img-top" src="https://i.pinimg.com/736x/d1/bc/77/d1bc777133ef71eb26ca380f5a30cdc0.jpg">
      </div> -->
      <!-- /.col-lg-3 -->

      <!-- <div class="col-lg-9"> -->
   
        {% if messages %}
          {% for message in messages %}
          <div class="alert alert-success alert-dismissible fade show" role="alert">
            <strong>{{ message }}</strong> 
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          {% endfor %}
        {% endif %}
        <!-- <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
          <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
          </ol>
          <div class="carousel-inner" role="listbox">
            <div class="carousel-item active">
              <img class="d-block" width="800" height="400" src="https://i.pinimg.com/474x/50/0d/dc/500ddc9658d909c69a2e4dc020d7dcd6.jpg" alt="First slide">
            </div>
            <div class="carousel-item">
              <img class="d-block" width="800" height="400" src="https://turboportal.net/uploads/posts/2014-04/1396941020__.jpg" alt="Second slide">
            </div>
            <div class="carousel-item">
              <img class="d-block" width="800" height="400" src="https://www.meme-arsenal.com/memes/b532a01e78fd8ac51909090252ccb049.jpg" alt="Third slide">
            </div>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="false"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="false"></span>
            <span class="sr-only">Next</span>
          </a>
        </div> -->
       

        <div class="row">
          {% for product in products %}
       
            <div class="product-item">
              <a href="{{ product.get_absolute_url }}"><img width=250 height=250 src="{{ product.image.url }} "></a>
              <div class="product-list">
                <h3>{{ product.title }}</h3>
                  <span class="price">{{ product.price }} руб.</span>
                  <a href="{% url 'add_to_cart' ct_model=product.get_model_name slug=product.slug %}" class="button">В корзину</a>
              </div>
              </div>
            <!-- <div class="card h-100">
              <a href="{{ product.get_absolute_url }}"><img class="card-img-top" src="{{ product.image.url }} " alt=""></a>
              <div class="card-body">
                <h4 class="card-title">
                  <a href="{{ product.get_absolute_url }}">{{ product.title }}</a>
                </h4>
                <h5>{{ product.price }} руб.</h5>
                <a href="{% url 'add_to_cart' ct_model=product.get_model_name slug=product.slug %}">
                  <button class="btn btn-danger">Добавить в корзину</button>
                </a> -->
              <!-- </div> -->
            
        
          {% endfor %}
        </div>
        <!-- /.row -->
      
      {% endblock content %}
      <!-- </div> -->
      <!-- /.col-lg-9 -->

    <!-- </div> -->
    <!-- /.row -->

  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-white">
    <div class="container">
      <p class="colortext">Copyright &copy; P-P SHOP (ВСЕ ПРАВА НА НАЗВАНИЕ ЗАЩИЩЕНЫ)</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>

</html>

mainapp/templates/beer_add.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% block content %}
<div class="row" style="margin-bottom: 50px; margin-top: 50px">
    <div class="col-md-6 offset-md-3">
        <h3 class='text-center'>Добавление нового пива</h3>
        <hr>
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" class="btn btn-success" value="Добавить">
        </form>
    </div>
</div>

{% endblock %}

mainapp/templates/profile.html
{% extends 'base.html' %}

{% block content %}
<style>
    table {
    font-family: "Lucida Sans Unicode", "Lucida Grande", Sans-Serif;
    font-size: 14px;
    text-align: left;
    border-collapse: collapse;
    border-radius: 20px;
    box-shadow: 0 0 0 10px #73b9e7;
    color: #452F21;
    }
    th {
    padding: 10px 8px;
    background: white;
    }
    table th:first-child {
    border-top-left-radius: 20px;
    }
    table th:last-child {
    border-top-right-radius: 20px;
    }
    td {
    border-top: 10px solid #F2906B;
    padding: 8px;
    background: white;
    }
    table td:first-child {
    border-bottom-left-radius: 20px;
    }
    table td:last-child {
    bord
    
    </style>
<h3 class="text-center mt-3 mb-3 ">Заказы пользователя {{ request.user.username }}</h3>
{% if not orders.count %}
<div class="col-md-12" style="margin-top: 300px; margin-bottom: 300px; margin-left: 300px;">
    <h3> У вас ещё нет заказов. <a href="{% url 'base' %}">Начните делать покупки</a></h3>
</div>

{% else %}
<div class="col-md-12" style="margin-bottom: 250px; margin-top: 250px;">

<table class="table">
    <thead>
        <th scope='col'>Номер</th>
        <th scope='col'>Статус</th>
        <th scope='col'>Сумма</th>
        <th scope='col'>Товар</th>
        <th scope='col'>Дополнительно</th>
    </thead>
    <tbody>
        {% for order in orders %}
            <tr>
                <th scope="row">{{ order.id }}</th>
                <td>{{ order.get_status_display }}</td>
                <td>{{ order.cart.final_price }} руб.</td>
                <td>
                    <ul>
                        {%for item in order.cart.products.all %}

                            <li>{{ item.product.title}} x {{item.qty}}</li>

                        {% endfor %}
                    </ul>
                </td>
                <td>
                    <button class="btn btn-info" data-toggle="modal" data-target="#exampleModal-{{ order.id }}">Дополнительно</button>
                    <div class="modal fade" id="exampleModal-{{ order.id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog modal-lg">
                          <div class="modal-content">
                            <div class="modal-header">
                              <h5 class="modal-title" id="exampleModalLabel">Детализация заказа</h5>
                              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                              </button>
                            </div>
                            <div class="modal-body">
                              <h4 class="text-center">Товар</h4>
                               <table class="table">
                                   <thead>
                                       <tr>
                                           <th scope="col">Наименование</th>
                                           <th scope="col">Изображение</th>
                                           <th scope="col">Цена</th>
                                           <th scope="col">Ко-во</th>
                                           <th scope="col">Общая цена</th>
                                       </tr>
                                   </thead>
                                   <tbody>
                                        {% for item in order.cart.products.all %}
                                        <tr>
                                            <th scope="row">{{ item.content_object.title }}</th>
                                            <td class="w-25"><img width=250 height=270 src="{{ item.content_object.image.url }}" ></td>
                                            <td><strong>{{ item.product.price }}</strong> руб.</td>
                                            <td>{{ item.qty }}</td>
                                            <td>{{ item.final_price }} руб.</td>
                                        </tr>
                                        {% endfor %}
                                        <tr>
                                            <td colspan="2"></td>
                                            <td>Итого: </td>
                                            <td>{{ order.cart.total_products }}</td>
                                            <td><strong>{{ order.cart.final_price }}</strong> руб.</td>
                                        </tr>
                                   </tbody>
                               </table>
                               <hr>
                               <h4 class="text-center">Дополнительная информация</h4>
                               <p>Имя: <strong>{{ order.first_name }}</strong></p>
                               <p>Фамилия: <strong>{{ order.last_name }}</strong></p>
                               <p>Телефон: <strong>{{ order.customer.phone }}</strong></p>
                            </div>
                            <div class="modal-footer">
                              <button type="button" class="btn btn-danger" data-dismiss="modal">Закрыть</button>
                            </div>
                          </div>
                        </div>
                      </div>
                    
                </td>
            </tr>  
             
        {% endfor %}
    </tbody>

</table>
</div>

{% endif %}

{%  endblock %}